apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-starter
  labels:
    app: ts-starter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ts-starter
  template:
    metadata:
      labels:
        app: ts-starter
    spec:
      containers:
      - name: ts-starter
        image: dimkk/ts-starter
        ports:
        - containerPort: 3030
---
apiVersion: v1
kind: Service
metadata:
  name: ts-starter-service
spec:
  selector:
    app: ts-starter
  ports:
    - protocol: TCP
      port: 3030
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ts-starter-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: ts-starter-service
          servicePort: 3030
  tls:
  - hosts:
    - k3s.dimkk.be
    secretName: cert-k3s-dimkk-be
